### ISSUE TITLE
Dead people can use sissm commands

### ISSUE THREAD

**Issue by DFSCompad** [schroeder-lvb/sissm#106]
Dead people can use sissm commands like pp, aa and 11. Is it possible to turn this off?

**Comment by schroeder-lvb** [comment]
Note to self:

Experiment with internal API char call from `pitacnomic` plugin:

`char *apiCharacterToName( char *characterID )`

A "dead" person should return null for `characterID`.

**Comment by schroeder-lvb** [comment]
Clarification:  Dead people should be blocked from using SISSM "two letter codes."  This is handled in pitacnomic plugin, and not picladmin.

Dead people should be able to use SISSM commands in general.  Admins and moderators must be able to issue SISSM commands while dead.

**Comment by schroeder-lvb** [comment]
tap point:

piantirush :: piantirushChatCB()

**Comment by schroeder-lvb** [comment]
[Staged for release in version 0.2.8]
