### ISSUE TITLE
Tideway is not in example.sissm.cfg

### ISSUE THREAD

**Issue by DFSCompad** [schroeder-lvb/sissm#111]
pidynbots.adjuster[20] "Tideway_Checkpoint_Security    	 
pidynbots.adjuster[21] "Tideway_Checkpoint_insurgents

**Comment by schroeder-lvb** [comment]
Thank you - will pick that up on the next release.

FYI missing entry is not harmful - it just doesn't make any bot adjustments (runs default).

[Staged for release in version 0.2.8]
