### ISSUE TITLE
do not show disconnect messages on round change

### ISSUE THREAD

**Issue by k0872** [schroeder-lvb/sissm#24]
is it possible to add a switch to not show disconnect messages at end of round, map vote and change state/.

**Comment by schroeder-lvb** [comment]
By "disconnect" do you mean player disconnect messages?   Please clarify - I think you are trying to prevent people from mass-quitting because they saw messages that others are disconnecting?

**Comment by schroeder-lvb** [comment]
This idea will not be implemented.

While good idea for server population retention, this feature 1) gives appearance of a software "bug" or inconsistent behavior when implemented, confusing the end users, 2) makes the code-base very complicated for very little dividend, 3) expect only to be used by a very small number of servers.

**Comment by schroeder-lvb** [comment]
Staged for release in Beta 0.1.0 - with minimal testing
