### ISSUE TITLE
pidynbots - add support for respawn co-op (soloenemies)

### ISSUE THREAD

**Issue by schroeder-lvb** [schroeder-lvb/sissm#60]
pidynbots - add support for "respawn co-op" checkpoint variant (soloenemies)

Feasibility research -> Protype/Testing -> Implementation

**Comment by DFSCompad** [comment]
Oh yeah, that is what we need. I would ask for it if its possible to program it. Soloenemies for minplayers and grow up for maxplayers.

**Comment by schroeder-lvb** [comment]
[Staged for release in Beta 2.1 (0.2.1)]
